Вторая лаба
AlexTheTrashGolem/KPI_labs_Belorusskij pull request #2
Opened 2019-10-16 08:57 UTC by bugagashenkj

2019-10-16 08:58 UTC, bugagashenkj commented
@nechaido @bugagashenkj

2019-10-16 08:59 UTC, bugagashenkj commented on OP_laba3.py
> +x=float(input())
```suggestion
x = float(input())
```

2019-10-23 08:36 UTC, bugagashenkj commented
@nechaido

2019-10-23 10:06 UTC, nechaido requested changes
Добавь задание и отформатируй код.

2019-10-23 10:06 UTC, nechaido commented on OP_laba3.py
> +x=float(input())
Почему это еще не исправлено?

2019-10-23 10:06 UTC, nechaido commented on OP_laba2.py
> +answer = (x * y <= 0 and y - x -1 >= 0)
```suggestion
answer = (x * y <= 0 and y - x - 1 >= 0)
```

2019-10-23 10:06 UTC, nechaido commented on OP_laba3.py
> +s=(s//0.001)/1000
Это очень не очевидная операция.

2019-10-30 21:41 UTC, ivan-tymoshenko reviewed
Please add tasks to PR.

2019-10-30 21:41 UTC, bugagashenkj commented on OP_laba2.py
> +<<<<<<< HEAD
Failed with merge commit. Fix, please.

2019-10-30 21:41 UTC, bugagashenkj commented on OP_laba2.py
> +answer = (x*y<=0 and y-x-1>=0)
```suggestion
answer = (x * y <= 0 and y - x - 1 >= 0)
```
Formatting problems throughout the code.

2022-04-27 18:12 UTC, closed without merging